# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import exchange_frame_pb2 as exchange__frame__pb2


class FrameGetterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FrameProcess = channel.unary_unary(
        '/exchangeframe.FrameGetter/FrameProcess',
        request_serializer=exchange__frame__pb2.InputFrame.SerializeToString,
        response_deserializer=exchange__frame__pb2.OutputFrame.FromString,
        )
    self.FrameProcessTemp = channel.stream_stream(
        '/exchangeframe.FrameGetter/FrameProcessTemp',
        request_serializer=exchange__frame__pb2.InputFrame.SerializeToString,
        response_deserializer=exchange__frame__pb2.OutputFrame.FromString,
        )
    self.FrameBoxProcess = channel.unary_stream(
        '/exchangeframe.FrameGetter/FrameBoxProcess',
        request_serializer=exchange__frame__pb2.InputFrame.SerializeToString,
        response_deserializer=exchange__frame__pb2.Box.FromString,
        )
    self.FrameBoxesBytesProcess = channel.unary_unary(
        '/exchangeframe.FrameGetter/FrameBoxesBytesProcess',
        request_serializer=exchange__frame__pb2.InputFrame.SerializeToString,
        response_deserializer=exchange__frame__pb2.BoxesBytes.FromString,
        )


class FrameGetterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FrameProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FrameProcessTemp(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FrameBoxProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FrameBoxesBytesProcess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FrameGetterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FrameProcess': grpc.unary_unary_rpc_method_handler(
          servicer.FrameProcess,
          request_deserializer=exchange__frame__pb2.InputFrame.FromString,
          response_serializer=exchange__frame__pb2.OutputFrame.SerializeToString,
      ),
      'FrameProcessTemp': grpc.stream_stream_rpc_method_handler(
          servicer.FrameProcessTemp,
          request_deserializer=exchange__frame__pb2.InputFrame.FromString,
          response_serializer=exchange__frame__pb2.OutputFrame.SerializeToString,
      ),
      'FrameBoxProcess': grpc.unary_stream_rpc_method_handler(
          servicer.FrameBoxProcess,
          request_deserializer=exchange__frame__pb2.InputFrame.FromString,
          response_serializer=exchange__frame__pb2.Box.SerializeToString,
      ),
      'FrameBoxesBytesProcess': grpc.unary_unary_rpc_method_handler(
          servicer.FrameBoxesBytesProcess,
          request_deserializer=exchange__frame__pb2.InputFrame.FromString,
          response_serializer=exchange__frame__pb2.BoxesBytes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'exchangeframe.FrameGetter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
