# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange_frame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exchange_frame.proto',
  package='exchangeframe',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x65xchange_frame.proto\x12\rexchangeframe\"\x1b\n\nInputFrame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"\x1c\n\x0bOutputFrame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\"Z\n\x03\x42ox\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04ymin\x18\x02 \x01(\x02\x12\x0c\n\x04xmax\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\x12\r\n\x05label\x18\x05 \x01(\x05\x12\x0c\n\x04\x63onf\x18\x06 \x01(\x02\"\x1b\n\nBoxesBytes\x12\r\n\x05\x62oxes\x18\x01 \x01(\x0c\x32\xbf\x02\n\x0b\x46rameGetter\x12G\n\x0c\x46rameProcess\x12\x19.exchangeframe.InputFrame\x1a\x1a.exchangeframe.OutputFrame\"\x00\x12O\n\x10\x46rameProcessTemp\x12\x19.exchangeframe.InputFrame\x1a\x1a.exchangeframe.OutputFrame\"\x00(\x01\x30\x01\x12\x44\n\x0f\x46rameBoxProcess\x12\x19.exchangeframe.InputFrame\x1a\x12.exchangeframe.Box\"\x00\x30\x01\x12P\n\x16\x46rameBoxesBytesProcess\x12\x19.exchangeframe.InputFrame\x1a\x19.exchangeframe.BoxesBytes\"\x00\x42\x33\n\x15io.grpc.exchangeframeB\x12\x45xchangeFrameProtoP\x01\xa2\x02\x03\x45XFb\x06proto3')
)




_INPUTFRAME = _descriptor.Descriptor(
  name='InputFrame',
  full_name='exchangeframe.InputFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='exchangeframe.InputFrame.frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=66,
)


_OUTPUTFRAME = _descriptor.Descriptor(
  name='OutputFrame',
  full_name='exchangeframe.OutputFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='exchangeframe.OutputFrame.frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=96,
)


_BOX = _descriptor.Descriptor(
  name='Box',
  full_name='exchangeframe.Box',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xmin', full_name='exchangeframe.Box.xmin', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ymin', full_name='exchangeframe.Box.ymin', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xmax', full_name='exchangeframe.Box.xmax', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ymax', full_name='exchangeframe.Box.ymax', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='exchangeframe.Box.label', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conf', full_name='exchangeframe.Box.conf', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=188,
)


_BOXESBYTES = _descriptor.Descriptor(
  name='BoxesBytes',
  full_name='exchangeframe.BoxesBytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='boxes', full_name='exchangeframe.BoxesBytes.boxes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=217,
)

DESCRIPTOR.message_types_by_name['InputFrame'] = _INPUTFRAME
DESCRIPTOR.message_types_by_name['OutputFrame'] = _OUTPUTFRAME
DESCRIPTOR.message_types_by_name['Box'] = _BOX
DESCRIPTOR.message_types_by_name['BoxesBytes'] = _BOXESBYTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputFrame = _reflection.GeneratedProtocolMessageType('InputFrame', (_message.Message,), dict(
  DESCRIPTOR = _INPUTFRAME,
  __module__ = 'exchange_frame_pb2'
  # @@protoc_insertion_point(class_scope:exchangeframe.InputFrame)
  ))
_sym_db.RegisterMessage(InputFrame)

OutputFrame = _reflection.GeneratedProtocolMessageType('OutputFrame', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTFRAME,
  __module__ = 'exchange_frame_pb2'
  # @@protoc_insertion_point(class_scope:exchangeframe.OutputFrame)
  ))
_sym_db.RegisterMessage(OutputFrame)

Box = _reflection.GeneratedProtocolMessageType('Box', (_message.Message,), dict(
  DESCRIPTOR = _BOX,
  __module__ = 'exchange_frame_pb2'
  # @@protoc_insertion_point(class_scope:exchangeframe.Box)
  ))
_sym_db.RegisterMessage(Box)

BoxesBytes = _reflection.GeneratedProtocolMessageType('BoxesBytes', (_message.Message,), dict(
  DESCRIPTOR = _BOXESBYTES,
  __module__ = 'exchange_frame_pb2'
  # @@protoc_insertion_point(class_scope:exchangeframe.BoxesBytes)
  ))
_sym_db.RegisterMessage(BoxesBytes)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025io.grpc.exchangeframeB\022ExchangeFrameProtoP\001\242\002\003EXF'))

_FRAMEGETTER = _descriptor.ServiceDescriptor(
  name='FrameGetter',
  full_name='exchangeframe.FrameGetter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=220,
  serialized_end=539,
  methods=[
  _descriptor.MethodDescriptor(
    name='FrameProcess',
    full_name='exchangeframe.FrameGetter.FrameProcess',
    index=0,
    containing_service=None,
    input_type=_INPUTFRAME,
    output_type=_OUTPUTFRAME,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FrameProcessTemp',
    full_name='exchangeframe.FrameGetter.FrameProcessTemp',
    index=1,
    containing_service=None,
    input_type=_INPUTFRAME,
    output_type=_OUTPUTFRAME,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FrameBoxProcess',
    full_name='exchangeframe.FrameGetter.FrameBoxProcess',
    index=2,
    containing_service=None,
    input_type=_INPUTFRAME,
    output_type=_BOX,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FrameBoxesBytesProcess',
    full_name='exchangeframe.FrameGetter.FrameBoxesBytesProcess',
    index=3,
    containing_service=None,
    input_type=_INPUTFRAME,
    output_type=_BOXESBYTES,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAMEGETTER)

DESCRIPTOR.services_by_name['FrameGetter'] = _FRAMEGETTER

# @@protoc_insertion_point(module_scope)
